cambiatus/backend

- lib/bespiral/commune/commune.ex
- lib/bespiral/db_listener.ex
- lib/bespiral/notifications/notifications.ex
- mix.exs
- priv/repo/migrations/20190920061915_verification_notification.exs
- test/bespiral/commune/commune_test.exs
- test/bespiral/commune/community_test.exs
- test/bespiral/commune/network_test.exs
- test/bespiral/notifications/notifications_test.exs
> Feature: verification request notifications

- lib/bespiral/db_listener.ex
> Use correct trigger name for claims_changed notification

- lib/bespiral/db_listener.ex
- lib/bespiral/notifications/notifications.ex
- mix.exs
- priv/repo/migrations/20191008061455_create_validation_function.exs
- priv/repo/migrations/20191008062042_create_validation_trigger.exs
- test/bespiral/notifications/notifications_test.exs
> Feature: validation notifications

- lib/bespiral/commune/commune.ex
- lib/bespiral_web/resolvers/commune.ex
- lib/bespiral_web/schema/commmune_types.ex
- test/bespiral_web/resolvers/commune_test.exs
-[x] Implement functionality to collect claims by an actor
> Feature: validations query

- lib/bespiral/db_listener.ex
- lib/bespiral_web/schema/commmune_types.ex
- priv/repo/migrations/20191016081948_new_community_function.exs
- priv/repo/migrations/20191016082541_new_community_trigger.exs
- test/bespiral_web/schema/resolvers/accounts_test.exs
- test/bespiral_web/schema/resolvers/chat_test.exs
- test/bespiral_web/schema/resolvers/commune_test.exs
- test/bespiral_web/schema/resolvers/notifications_test.exs
- test/bespiral_web/schema/subscriptions/new_community_test.exs
- test/support/subscription_case.ex
> Feature: new community subscription

- lib/bespiral/commune/commune.ex
- lib/bespiral_web/resolvers/commune.ex
- lib/bespiral_web/schema/commmune_types.ex
- test/bespiral_web/schema/resolvers/commune_test.exs
> Feature: community claims

- lib/bespiral/db_listener.ex
- lib/bespiral/notifications/notifications.ex
- lib/bespiral_web/schema.ex
- lib/bespiral_web/schema/notification_types.ex
- mix.exs
- priv/repo/migrations/20191108093249_create_notification_history_function.exs
- priv/repo/migrations/20191108132545_create_notification_history_trigger.exs
- test/bespiral_web/schema/resolvers/notifications_test.exs
- test/bespiral_web/schema/subscriptions/new_community_test.exs
- test/bespiral_web/schema/subscriptions/notifications_test.exs
- test/support/subscription_case.ex
> Feature: Notifications Subscripitions

- lib/bespiral_web/schema/commmune_types.ex
> Use float for sale price

- lib/bespiral_web/resolvers/commune.ex
- lib/bespiral_web/schema/commmune_types.ex
- mix.exs
- test/bespiral_web/schema/resolvers/commune_test.exs
This is needed by @pancakem to finish https://github.com/cambiatus/frontend/issues/41
> Feature: transfer query

- lib/bespiral_web/schema/commmune_types.ex
- mix.exs
- test/bespiral_web/schema/resolvers/commune_test.exs
> Add to and from profiles to account to the transfer object

- .github/contributing.md
- .github/pull_request_template.md
- .github/setup.md
- README.md
> Feature: Readme and contribution guide

- lib/bespiral/accounts/user.ex
- lib/bespiral/auth/auth.ex
- lib/bespiral/auth/invitation.ex
- lib/bespiral/commune/check.ex
- lib/bespiral/commune/commune.ex
- lib/bespiral/commune/validator.ex
- lib/bespiral/mails/user_mail.ex
- lib/bespiral/notifications/notifications.ex
- lib/bespiral_web/controllers/invite_controller.ex
- priv/repo/migrations/20200225181540_new_invitations.exs
- test/bespiral/auth/auth_test.exs
- test/bespiral/auth/invitation_test.exs
- test/bespiral_web/controllers/auth_controller_test.exs
- test/bespiral_web/schema/resolvers/commune_test.exs
- test/support/factory.ex
- All tests fixed
- Behaviour that was implemented on #28 was corrected
- Start working on a new invitation. Fixed tests and added a new migration
- Query objectives in Graphql to see that they are now ordered by date
- run `mix test` to check all passing tests
> Fix all tests and begin working on new invitation

- config/prod.exs
- config/test.exs
- lib/cambiatus_web/resolvers/commune.ex
- lib/cambiatus_web/schema/commmune_types.ex
- test/cambiatus/auth/invitation_id_test.exs
- test/cambiatus_web/schema/resolvers/commune_test.exs
Add invitation graphql objects. Part of  https://github.com/cambiatus/frontend/issues/158
`mix test`
> Add invitation to our graphql api

- .github/workflows/test.yml
- config/test.exs
- lib/cambiatus/accounts/transfers.ex
- test/cambiatus_web/schema/resolvers/commune_test.exs
Closes #45 
This PR introduces Github actions, which is a Github-integrated CI solution. It builds the project, runs tests and linters. It's a foundation for adding continuous deployment, which can be done when we improve our AWS infrastructure.
Check the Actions tab :)
> Use github actions and fix test suite

- .github/workflows/test.yml
This fixes the failing job pushImage
> Pin ubuntu versions to 18.04

- lib/cambiatus_web/schema/kyc_types.ex
Closes N/A
Returns unique identifiers on address queries to be used by the frontend on mutations
1. Open the graphql playground
2. Use the `country` query
> Add id field to country, state, city and neighborhood

- priv/repo/migrations/20201012162709_add_proof_actions.exs
Adds new columns to `actions` and `claims` tables
`mix ecto.migrate`
> Adds columns to actions and claims

- lib/cambiatus/kyc/address.ex
- lib/cambiatus/kyc/kyc.ex
- lib/cambiatus/kyc/kyc_data.ex
- lib/cambiatus_web/resolvers/kyc.ex
- lib/cambiatus_web/schema/kyc_types.ex
- test/cambiatus/kyc/kyc_data_test.exs
- test/cambiatus_web/schema/resolvers/kyc_test.exs
Closes #84 
For easier frontend error message consumption this PR improves:
- Error message from kyc changeset validation functions
- Delete_kyc and delete_address mutations and its error messages
Run mix phx.server command
Open http://localhost:4000/api/graphiql
Run the mutations listed below changing their input fields to reproduce the error messages.
- upsertKyc
- upsertAddress
- deleteKyc
- deleteAddress
Wrong input fields examples for testing the error message behavior
- accountId: "victorgdev1" (non-existent account example)
- document: "11111111b" (invalid document entry example)
- documentType: "cedula" (invalid document_type example)
- phone: "4443333b" (invalid phone entry example)
- userType: "natura" (invalid user_type example)
- countryId: "b" (invalid country_id example)
- …
> Error msg improvements + KYC mutations refactoring

- README.md
Closes #92 #93 
Updates backend documentation
> Backend documentation update

- LICENSE
Closes backend application license update
Adds license file to the frontend repository.
The license file content is related to the AGPL license that came from this [website](https://www.gnu.org/licenses/agpl-3.0.md).
1- Open frontend repository page
2- Find and open license file
> Creates LICENSE file for the backend application

- config/dev.exs
Closes N/A.
Actualize some env variables to be like on the Staging server. This is just for convenience.
Run the project on your local machine, nothing should fail.
> Updates some of the DEV ENV settings

- README.md
Closes #116 
- Update the link of EOS to the correct one
> Fix link to EOS in Readme file

- .formatter.exs
- lib/cambiatus/commune/commune.ex
- lib/cambiatus/commune/community.ex
- lib/cambiatus/commune/subdomain.ex
- lib/cambiatus_web/resolvers/commune.ex
- lib/cambiatus_web/schema/commmune_types.ex
- priv/repo/migrations/20190613185018_add_index_to_created_at_in_transfers.exs
- priv/repo/migrations/20190704185323_change_sales_structure.exs
- priv/repo/migrations/20190714210029_add_available_sales_view.exs
- priv/repo/migrations/20190724200456_add_track_stock_to_sales_table.exs
- priv/repo/migrations/20190724200510_recreate_materialized_view_for_sales.exs
- priv/repo/migrations/20190724200646_remove_buy_option_from_sales.exs
- priv/repo/migrations/20191016082541_new_community_trigger.exs
- priv/repo/migrations/20191114011900_default_claim_is_verified.exs
- priv/repo/migrations/20210421232940_subdomains.exs
- priv/repo/migrations/20210421234356_community_subdomain.exs
- priv/repo/migrations/20210421235832_subdomain_initial_fill.exs
- test/cambiatus/commune/network_test.exs
- test/support/factory.ex
* Format migrations
* Add subdomain table logic
* Add GraphQL query
* Adjust tests and releations for subdomain
* Adjust graphql query
Closes #
> Support subdomains configuration (#149)

- .github/contributing.md
Since we are an open source community our `readme` should strive to encompass developers of all experience. This can mean a beginning developer will want to make their first PR request; thus, we should explain the PR and release process.
* I have update our contribution to reflect accurately our PR and release process. 
* Fixed some grammatical error
Review content change.
> Contribution documentation update

- priv/repo/migrations/20220128202802_increase_bio_size.exs
Closes #206 
- change bio to text, so we can store longer values
- mix test
> Migrate user's bio to text

- lib/cambiatus/kyc/kyc_data.ex
- test/cambiatus/auth/sign_up_test.exs
- test/cambiatus/kyc/kyc_data_test.exs
> Improvement on kyc error message when document is not valid

- README.md
> Updated README.md to inform about exiftool

- priv/gettext/es-ES/LC_MESSAGES/default.po
Closes #267 
Adicionar tradução em espanhol para o corpo do email de digest
> Added spanish translation for digest email

- priv/repo/migrations/20220806190533_session_token_as_text.exs
Closes #268
- Adjust field on auth_sessions table to be text instead of varchar(255)
N/A
> Adjust field size

- config/config.exs
- lib/cambiatus_web/controllers/manifest_controller.ex
- lib/cambiatus_web/controllers/rich_link_controller.ex
- lib/cambiatus_web/schema/commune_types.ex
- lib/cambiatus_web/templates/email/claim.html.eex
- lib/cambiatus_web/templates/email/monthly_digest.html.eex
- lib/cambiatus_web/templates/email/transfer.html.eex
Closes #279 
Remove `non_null` constraint on the GraphQl schema for community logo
> Removed non_null contraint on GraphQl schema for community logo

- priv/repo/migrations/20221125170725_session_user_agent_as_text.exs
- test/cambiatus/auth_test.exs
Closes N/A
Reported by @luizhaddad, a user from SurfLimpo is trying to login using instagram browser. This PR fixes this problem
- Change field
- `mix test` should be enough as there is a test case.
> Adjust type for the user agent field
