lib/bespiral/commune/commune.ex
lib/bespiral/commune/transfer.ex
lib/bespiral/db_listener.ex
lib/bespiral/notifications/notification_history.ex
lib/bespiral/notifications/notifications.ex
lib/bespiral/notifications/payload.ex
lib/bespiral/notifications/push_subscriptions.ex
lib/bespiral_web/resolvers/notifications.ex
lib/bespiral_web/schema.ex
lib/bespiral_web/schema/commmune_types.ex
lib/bespiral_web/schema/notification_types.ex
mix.exs
priv/repo/migrations/20191001194938_add_notification_history.exs
test/bespiral/notifications/notification_history_test.exs
test/bespiral_web/resolvers/notifications_test.exs
test/support/factory.ex

This PR aims to implemente the backend part for the notification history screen, seen here:
https://projects.invisionapp.com/d/main#/console/17335338/367779185/preview

Add NotificationHistory table, with GraphQL, save shop and transfer notifications

---

lib/bespiral/commune/community.ex
lib/bespiral/commune/mint.ex
lib/bespiral/db_listener.ex
lib/bespiral/notifications/notifications.ex
lib/bespiral_web/schema/commmune_types.ex
lib/bespiral_web/schema/notification_types.ex
mix.exs
priv/repo/migrations/20191113083016_create_mint_function.exs
priv/repo/migrations/20191113083443_create_mint_trigger.exs
test/bespiral/notifications/notifications_test.exs
test/support/factory.ex

Feature: mint notifications

---

lib/bespiral_web/schema/commmune_types.ex
mix.exs

Expand sale query to allow us to query related community details, used on the transfer screen: https://www.figma.com/file/X0ROabI93lbH0YsHDiwcFf/shop---mobile?node-id=1%3A1159

Expand sale query to allow for community details load

---

lib/bespiral/commune/commune.ex

Closes #25 
Lists objectives in ascending other

Sort objectives

---

lib/cambiatus/accounts/transfers.ex

Fixes a bug from #43 caused by using `DateTime.add/3` which works only for Elixir 1.8.0 and above.
Use a custom function for adding one day to the DateTime variable.
- Tests from `test/cambiatus_web/schema/resolvers/accounts_test.exs` should work.
- DatePicker from [frontend branch](https://github.com/cambiatus/frontend/pull/253) should not cause 500 error.
- Sentry should not report a bug after choosing a date from Date Picker on Frontend.

Fix for BACKEND-1C: adding one day to DateTime for Elixir 1.7.2

---

lib/cambiatus/commune/community.ex
lib/cambiatus_web/schema/commmune_types.ex
priv/repo/migrations/20200619185211_change_has_actions_to_has_objectives.exs
test/cambiatus_web/schema/resolvers/commune_test.exs

This PR makes naming more consistent across the project. Contracts and the frontend are already using `has_objectives`, so the backend should follow :)

Rename has_actions to has_objectives

---

config/config.exs
config/dev.exs
config/prod.exs

This is already done by ex_aws by default, and specifying it again seems
to break our docker deployment
Run the backend container from our infra repository

Remove unneeded access key configs

---

config/dev.exs
lib/cambiatus/auth/auth.ex
lib/cambiatus/eos.ex
lib/cambiatus_web/resolvers/accounts.ex
lib/cambiatus_web/schema/account_types.ex
test/cambiatus/auth/auth_test.exs
test/cambiatus_web/schema/resolvers/accounts_test.exs
test/support/mocks/eosrpc_helper_mock.ex

Closes #57 
Introduces a new mutation for creating new users. This is necessary for the future implementation of know-your-customer functionality.
1. Open up the playground (http://localhost:4000/api/graphiql)
2. Run the mutation `createUser`

Add signup mutation

---

lib/cambiatus_web/schema/account_types.ex
test/cambiatus_web/schema/resolvers/accounts_test.exs

Closes N/A. This PR adds KYC and address to the Profile GraphQl query. Related to cambiatus/frontend/pull/346 and some other issues which need this info on the frontend.
Add `kyc` and `address` fields to the Profile query to have this info on the frontend. Here's the full query:
```graphql
{
profile(input: {account: "andreymiskov"}) {
address {
street
number
zip
country {
name
}      
state {
name
}
city {
name
}
neighborhood {
name
}
}
kyc {
userType
documentType
document
phone
isVerified
country {
name
}
}
}
}
```
Run tests or/and try to use the query above from the GraphiQl interface.

Add KYC info and the address to the Profile query

---

lib/cambiatus_web/schema/kyc_types.ex

----
Closes N/A
Makes states, cities and neighborhoods non-null, as none of these should ever be null. For example, a city with no neighborhoods should return an empty list.
1. Access the graphql playground and check the schema

Make states, cities and neighborhoods non-null

---

lib/cambiatus/kyc/address.ex
lib/cambiatus/kyc/city.ex
lib/cambiatus/kyc/country.ex
lib/cambiatus/kyc/kyc_data.ex
lib/cambiatus/kyc/neighborhood.ex
lib/cambiatus/kyc/state.ex

Closes N/A.
This PR fixes a minor issue with the permitted keys in [`cast/4`](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/4) function:
- the permitted keys should be passed as the third argument to the `cast/4` function;
- these keys must be atoms.
We had `@optional_fields` passed as 4th argument in some places. This caused the issue when the optional arguments, like `number` in Address, weren't updated.
- Pass all fields as the third argument;
- Make sure all permitted fields are atoms.
Try to run `changeset` from the e.g. `Address` on the master branch, the `number` field won't be added:
```elixir
alias Cambiatus.Kyc.Address
Address.changeset(%Address{}, %{
account_id: 1,
country_id: 1,
street: "Elm Street",
neighborhood_id: 1,
city_id: 1,
state_id: 1,
zip: "10102",
number: "33"
}) …
```

Fix changeset permitted keys

---

lib/cambiatus_web/schema/kyc_types.ex

Closes N/A.
Use `:id` type for countries, cities, states, and neighborhoods in KYC and Address input objects. See [this comment](https://github.com/cambiatus/backend/pull/80#issuecomment-692209332) for more context.

Use id type instead of string

---

lib/cambiatus/upload.ex
lib/cambiatus_web/controllers/upload_controller.ex
test/cambiatus/upload_test.exs
test/cambiatus_web/schema/resolvers/accounts_test.exs
test/support/mocks/ex_aws_mock.ex

----
Closes #73
1. Adds content type information to S3 uploads
1. Run `mix test`
2. Upload a file to the `/upload` endpoint, send a request to the returned URL and confirm the Content-Type header is correct

Add content-type information when uploading to S3

---

lib/cambiatus/kyc/address.ex
lib/cambiatus/kyc/kyc_data.ex

Closes #82 
Adds the account_id foreign constraint to the Address changeset
Adds the account_id and country_id foreign constraint to the KYC changeset
Go to the GraphiQL Playground
Run the upsertKYC and/or upsertAddress mutations
**Examples For Testing**
```
// UpsertKYC
mutation {
upsertKyc( input: 
{ accountId: "andreymisk",  // account does not exist
countryId: "1", 
document: "1231231231", 
documentType: "nite", 
phone: "11948340013", 
userType: "natural"})
{ phone
country { name } }
}
// UpsertAddress
mutation {
upsertAddress( input: 
{ accountId: "andreymisk",
cityId: "1",
countryId: "1", 
neighborhoodId: "1",
number: "123",
stateId: "1",
street: "Elm street",
zip: "10101"})
{ country { name } }
}
```
BEFORE
AFTER

Adds fkey constraint to KYC & Address changeset

---

lib/cambiatus_web/controllers/auth_controller.ex

Instead of simply removing the route, I opted to instead redirect to our graphql endpoint using the 301 Moved Permanently status code
Closes #70

Remove the old sign up API

---

lib/cambiatus/commune/commune.ex

Closes an issue with Claims listing on the Analysis page from the [frontend/409](https://github.com/cambiatus/frontend/issues/409)
Change the query for retrieving all claims to analyze for the given validator from the given community.
- Login as a validator for some Claim.
- Go to the `dashboard/analysis` page, try to approve/disapprove some Claims.
- The number of Claims on this page should stay the same, only the status for the current user should change.
- Other verifiers should also have the right amount of Claims on their Analysis pages.

Fix analysis page listing

---

lib/cambiatus_web/resolvers/commune.ex
lib/cambiatus_web/schema/commmune_types.ex
test/cambiatus_web/schema/resolvers/commune_test.exs

Closes N/A
- Removes `communityPreview` query but keep the type
- Change `invite` to show `communityPreview` type instead of `community`
- Simplify params on `invite`
- `mix test`
- Deploy on staging
- Check with @NeoVier if its what he needs

Adjust invite to have a community preview

---

lib/cambiatus/commune/commune.ex
lib/cambiatus/commune/community.ex
lib/cambiatus/commune/community_photos.ex
lib/cambiatus_web/schema/commmune_types.ex
test/support/channel_case.ex
test/support/subscription_case.ex

Closes N/A
- Fixes some warnings
- Add sorting to community photos
- Add timestamps to community photos on GraphQL
- `mix test` as always
- Upload some photos and make sure they are sorted by date. You can always

Add sorting to community photos

---

lib/cambiatus/commune/claim.ex
lib/cambiatus/commune/commune.ex
lib/cambiatus_web/resolvers/commune.ex
lib/cambiatus_web/schema/commune_types.ex
lib/cambiatus_web/schema/relay_types.ex
test/cambiatus_web/schema/resolvers/commune_test.exs

Improve semantics of our claim queries

---

lib/cambiatus/commune/community.ex
test/cambiatus/commune/community_test.exs

Closes #230 
Run `mix test test/Cambiatus/Commune/community_test.exs`

Moved community description to optional fields

---

lib/cambiatus_web/controllers/rich_link_controller.ex
lib/cambiatus_web/templates/rich_link/rich_link.html.eex
lib/cambiatus_web/views/rich_link_view.ex
priv/gettext/amh-ETH/LC_MESSAGES/default.po
priv/gettext/es-ES/LC_MESSAGES/default.po
priv/gettext/pt-BR/LC_MESSAGES/default.po
test/cambiatus_web/controllers/rich_link_controller_test.exs

Closes #245 
Atualizar a funcionalidade do rich link preview para mostrar o preço dos produtos no título da preview
[Link do Figma](https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=1672%3A6427)

Added price and creator to description

---

lib/cambiatus/shop.ex
lib/cambiatus/shop/product.ex
test/cambiatus_web/schema/resolvers/shop_test.exs
test/test_helper.exs

Closes N/A
- Adjust the way we relate product and product categories
- Add extra info (community_id and creator_id) to product when creating
- Make sure we can create new products with categories related
- Make sure we can change categories of an existing product that already had categories 
- `mix test`

Fix two wrong instances of product_category mutations

---

priv/repo/migrations/20220808193453_no_empty_string_constraint.exs
priv/repo/null_strings.exs
priv/repo/replace_empty_strings_ingested_with_nil.exs

Closes #266 
Criar script para detectar valores `""` já existentes na db e atualizá-los para `nil`
1. Procurar na db por valores com `''`
2. Executar `iex -S mix priv/repo/null_string.exs`
3. Verficar se os valores foram alterados para `NULL`

Script para atualização de campos com string vazia

---

lib/cambiatus/db_listener.ex

Closes #285 
Uncomment lines that prevented oban from inserting mails into the mailer queue

Removed comments that stopped oban from queueing emails

---

lib/cambiatus/workers/contribution_paypal_worker.ex
lib/cambiatus/workers/monthly_digest_worker.ex

This is a subset of cambiatus/backend#306
Closes cambiatus/backend#304
Return 2 tuple errors to Oban. 4 tuple errors are generated when `Multi.new` is upstream of `Repo.transaction`.
Existing unit test coverage. They passed for me locally, after running `mix format` and `mix credo`.
I am submitting two versions of this change. This PR addresses the error handling. The next PR will have that, and it will include the credo check.

Give errors to Oban as 2 tuples
